[tool.poetry]
name = "poetry shell"
version = "poetry show --latest"
description = ""
authors = ["Max9222 <maxoog@bk.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
